### ISSUE TITLE
kotlin multiplatform debugging - paths

### ISSUE THREAD

**Issue by koush** [fwcd/kotlin-debug-adapter#52]
Kotlin multiplatform has a slightly different directory output structure that the debug adapter or related extension does not seem to recognize.

For example, moving ```core/jvm/test/``` to the root project ```core/test/``` makes the launch work properly. I'm not sure where to begin to fix this, but diagnosing the issue was easy enough.

![Foo_kt_—_scratch](https://user-images.githubusercontent.com/73924/95949765-40565a80-0da8-11eb-9364-ec430d245c1a.png)

**Comment by fwcd** [comment]
The issue here is that the Kotlin Debug Adapter currently relies on [hardcoded paths](https://github.com/fwcd/kotlin-debug-adapter/blob/a2a2332a081286256c790d7eb51cf0798d808fab/adapter/src/main/kotlin/org/javacs/ktda/classpath/ProjectClassesResolver.kt#L14), which is obviously not a very robust solution. A possible solution would be to write (and invoke) a Gradle script, like we do to locate dependencies, but for [output classes](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSetOutput.html).

**Comment by koush** [comment]
Alright, I submitted a pull request that should fix it, but unfortunately I was unable to test the resolution. The build instructions seem out of date.

```
Mac:kotlin-debug-adapter[master]$ ./gradlew :editors:vscode:prepare

FAILURE: Build failed with an exception.

* What went wrong:
Project 'editors' not found in root project 'kotlin-debug-adapter'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 491ms

```
